import jsPDF from 'jspdf'
import type { ArticleMetadata } from '../../lib/types'
import type { ThemeColors } from './config'

export const generateTitlePage = (
    doc: jsPDF,
    metadata: ArticleMetadata,
    coverImage: string | null,
    config: any,
    colors: ThemeColors,
    fonts: any
): number => {
  // Background Color for Title Page
  doc.setFillColor(colors.sidebar)
  doc.rect(0, 0, config.pageWidth, config.pageHeight, 'F')
  
  const TITLE_START_X = config.margin + 10
  let currentY = config.margin + 30
  
  const titlePageTextMain = '#FFFFFF'
  const titlePageTextSecondary = '#E5E7EB' 
  
  // 1. Author Name
  doc.setFont(fonts.ui, 'normal') 
  doc.setFontSize(11)
  doc.setTextColor(titlePageTextSecondary)
  doc.text(metadata.author.toUpperCase(), TITLE_START_X, currentY, { charSpace: 1.5 })
  currentY += 15
  
  // 2. Title with Accent Bar (Dynamic Scaling)
  doc.setFont(fonts.title, 'bold')
  
  let titleFontSize = 42
  if (metadata.title.length > 80) titleFontSize = 32
  if (metadata.title.length > 150) titleFontSize = 26
  
  doc.setFontSize(titleFontSize)
  doc.setTextColor(titlePageTextMain)
  
  const TITLE_X_OFFSET = 12
  const MAX_TITLE_WIDTH = config.pageWidth - TITLE_START_X - 10 - TITLE_X_OFFSET
  const titleLines = doc.splitTextToSize(metadata.title.toUpperCase(), MAX_TITLE_WIDTH)
  const titleBlockHeight = titleLines.length * (titleFontSize * 0.3527 * 1.15)
  
  // Accent Bar
  doc.setFillColor(colors.accent)
  doc.rect(TITLE_START_X, currentY - 8, 4, titleBlockHeight + 2, 'F') 
  doc.text(titleLines, TITLE_START_X + TITLE_X_OFFSET, currentY)
  
  currentY += titleBlockHeight + 20
  
  // 3. Cover Image 
  if (coverImage) {
     try {
        const imgProps = doc.getImageProperties(coverImage)
        const imgRatio = imgProps.height / imgProps.width
        const imgWidth = config.pageWidth 
        const imgHeight = imgWidth * imgRatio
        
        doc.addImage(coverImage, 'JPEG', 0, currentY, imgWidth, imgHeight)
        
        currentY += imgHeight + 20
     } catch (e) {
        console.warn('Cover image error', e)
     }
  }
  
  // 4. Metadata
  let metaY = config.pageHeight - 60
  if (currentY > metaY) metaY = currentY + 10
  
  doc.setFont(fonts.ui, 'bold')
  doc.setFontSize(9)
  doc.setTextColor(titlePageTextSecondary)
  
  if (metadata.date) {
    doc.text(`PUBLISHED: ${metadata.date.toUpperCase()}`, TITLE_START_X, metaY)
    metaY += 6
  }
  if (metadata.handle) {
      doc.text(metadata.handle, TITLE_START_X, metaY)
      metaY += 6
  }
  
  // URL Link
  metaY += 4
  doc.setFontSize(9)
  doc.setTextColor(colors.accent)
  doc.textWithLink('Read on X', TITLE_START_X, metaY, { url: metadata.url })

  // 5. Badge Footer (Linked)
  const badgeTextMain = "PDF GENERATED BY X-ARTICLE-EXPORTER | BY "
  const badgeHandle = "@KORECODES"
  const fullBadgeText = badgeTextMain + badgeHandle
  
  doc.setFontSize(7)
  doc.setFont(fonts.ui, 'bold')
  const fWidth = doc.getTextWidth(fullBadgeText) + 12
  const fHeight = 8
  const fX = config.pageWidth - fWidth - 10
  const fY = config.pageHeight - fHeight - 10
  
  doc.setFillColor(titlePageTextSecondary)
  doc.roundedRect(fX, fY, fWidth, fHeight, 1, 1, 'F') 
  
  doc.setTextColor(colors.sidebar)
  doc.text(badgeTextMain, fX + 6, fY + 5.5)
  
  const mainTextWidth = doc.getTextWidth(badgeTextMain)
  doc.setTextColor(colors.accent)
  doc.text(badgeHandle, fX + 6 + mainTextWidth, fY + 5.5)
  
  doc.link(fX, fY, fWidth, fHeight, { url: 'https://x.com/korecodes' })
  
  return currentY
}

export const finalizeStandardPages = (
    doc: jsPDF,
    metadata: ArticleMetadata,
    config: any,
    colors: ThemeColors,
    fonts: any,
    isDark: boolean
) => {
    const totalPages = doc.getNumberOfPages()
  
    // Skip Page 1 (Title)
    for (let p = 2; p <= totalPages; p++) {
        doc.setPage(p)
        // Draw Sidebar
        doc.setFillColor(colors.sidebar)
        doc.rect(0, 0, config.sidebarWidth, config.pageHeight, 'F')
        
        // Footer Line
        doc.setDrawColor(colors.secondary)
        doc.setLineWidth(0.5)
        doc.line(
           config.contentStart, 
           config.pageHeight - 20, 
           config.pageWidth - config.margin, 
           config.pageHeight - 20
        )
        
        // Footer Title
        doc.setFont(fonts.ui, 'italic')
        doc.setFontSize(9)
        doc.setTextColor(colors.secondary)
        
        const footerTitle = metadata.title.length > 50 ? metadata.title.substring(0, 50) + '...' : metadata.title
        doc.text(
           footerTitle, 
           config.pageWidth - config.margin, 
           config.pageHeight - 15, 
           { align: 'right' }
        )
        
        // Page Number
        doc.setFont(fonts.ui, 'bold')
        doc.setFontSize(12)
        doc.setTextColor(isDark ? '#FFFFFF' : '#FFFFFF') 
        doc.text(`${p}`, config.sidebarWidth / 2, config.pageHeight - 15, { align: 'center' })
    }
}

export const generateTOC = (
    doc: jsPDF,
    tocEntries: { text: string, page: number, level: number }[],
    config: any,
    colors: ThemeColors,
    fonts: any,
    tocPagesCount: number
) => {
    let currentTocPage = 0
    let tocY = config.margin + 10
    
    doc.setPage(2)
    // TOC Title
    doc.setFont(fonts.title, 'normal')
    doc.setFontSize(32)
    doc.setTextColor(colors.text)
    doc.text('TABLE OF CONTENTS', config.contentStart, tocY)
    tocY += 25
    
    doc.setFont(fonts.body, 'normal')
    doc.setFontSize(12)
    
    tocEntries.forEach((entry, i) => {
        // Check for page break within TOC pages
        if (tocY > config.pageHeight - config.margin - 20) {
            currentTocPage++
            // Switch to naturally next page (which we already inserted)
            const nextPageIndex = 2 + currentTocPage
            if (nextPageIndex <= 1 + tocPagesCount) {
               doc.setPage(nextPageIndex)
               tocY = config.margin + 20
            }
        }
        
        const roman = (num: number) => {
           const lookup: any = {M:1000,CM:900,D:500,CD:400,C:100,XC:90,L:50,XL:40,X:10,IX:9,V:5,IV:4,I:1}
           let str = '', q = num
           for (let i in lookup) {
               while (q >= lookup[i]) { str += i; q -= lookup[i] }
           }
           return str
        }
        
        const prefix = entry.level === 1 ? `${roman(i+1).padEnd(5)}` : '  '
        const title = entry.text.length > 55 ? entry.text.substring(0, 55) + '...' : entry.text
        
        const targetPageNum = entry.page + tocPagesCount
        
        const ROW_Y = tocY
        
        doc.setTextColor(colors.text)
        doc.setFont(fonts.body, 'normal')
        doc.text(prefix, config.contentStart, ROW_Y)
        
        const titleX = config.contentStart + 15
        
        doc.setTextColor(colors.accent)
        doc.setFont(fonts.body, 'bold')
        doc.text(title, titleX, ROW_Y)
        
        const textWidth = doc.getTextWidth(title)
        doc.setDrawColor(colors.accent)
        doc.setLineWidth(0.3)
        doc.line(titleX, ROW_Y + 1, titleX + textWidth, ROW_Y + 1)
        
        doc.setTextColor(colors.text)
        doc.setFont(fonts.body, 'normal')
        doc.text(
           `${targetPageNum}`, 
           config.pageWidth - config.margin, 
           ROW_Y, 
           { align: 'right' }
        )
        
        doc.link(config.contentStart, ROW_Y - 5, 140, 10, { pageNumber: targetPageNum })
        tocY += 12
    })
}

export const generateNotesPage = (
    doc: jsPDF,
    config: any,
    colors: ThemeColors,
    fonts: any
) => {
  doc.addPage()
  doc.setFillColor(colors.bg)
  doc.rect(0, 0, config.pageWidth, config.pageHeight, 'F')
  
  // Header
  doc.setFont(fonts.title, 'bold')
  doc.setFontSize(24)
  doc.setTextColor(colors.text)
  doc.text('NOTES', config.margin, config.margin + 10)
  
  // Rule Lines
  doc.setDrawColor(colors.border)
  doc.setLineWidth(0.2)
  
  const startNotesY = config.margin + 30
  const endNotesY = config.pageHeight - config.margin
  const lineSpacing = 10
  
  for (let y = startNotesY; y < endNotesY; y += lineSpacing) {
      doc.line(config.margin, y, config.pageWidth - config.margin, y)
  }
  
  // Footer Badge for End Page
  doc.setFont(fonts.ui, 'italic')
  doc.setFontSize(10)
  doc.setTextColor(colors.secondary)
  doc.text('Generated by X Articles Exporter', config.pageWidth / 2, config.pageHeight - 15, { align: 'center' })
}
